#!/bin/bash

##############################################################################
# This script should be executed by the holder of the Cleanfeed signing key. #
##############################################################################

# Export the working copy from the repository to the web server and create a
# diff file against it.

SOURCE='svn+ssh://cleanfeed@snorky.mixmin.net/home/cleanfeed/svn-repository/cleanfeed/trunk'
DESTDIR='/tmp'
ORIGINAL='/crypt/home/crooks/cleanfeed/branches/cleanfeed-20020501/cleanfeed'
WEBUSER='news@snorky'
WEBDIR='/var/www/cleanfeed'

# Export the repository
echo "Exporting Cleanfeed"
svn export ${SOURCE}/cleanfeed ${DESTDIR}/cleanfeed

#Sign the cleanfeed export
echo "Signing Export"
gpg --armor --detach-sign ${DESTDIR}/cleanfeed

# Create a Diff
echo "Create Diff file"
diff -uN -Eb $ORIGINAL ${DESTDIR}/cleanfeed > ${DESTDIR}/cleanfeed.diff

# Copy it to the webserver
scp ${DESTDIR}/cleanfeed.asc ${WEBUSER}:${WEBDIR}
scp ${DESTDIR}/cleanfeed.diff ${WEBUSER}:${WEBDIR}
scp ${DESTDIR}/cleanfeed ${WEBUSER}:${WEBDIR}
